### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by 0ceanSlim** [MetroWind/dwm2-tools#3]
Would you like to help with my take on the app? It should be a lot easier to work with than this rust app you've made here. 

I threw it together this morning and styled some this afternoon. Please try for yourself and let me know what you think :)

https://github.com/0ceanslim/dwm-app

**Comment by MetroWind** [comment]
Nice! I actually started this project with a Flask app. This version is a Rust rewrite.

I’m pretty much done with this though, beyond fixing factual data errors.

**Comment by 0ceanSlim** [comment]
Would you like to help expand on mine? I would love to have a little more functionality to it. I've got a lot of good ideas. 

The current version is running at my domain if you wanna check it out. https://dwm.happytavern.co I want to make the monster names clickable in the breeding info screens as well as add items / skills data and more stuff

**Comment by MetroWind** [comment]
> Would you like to help expand on mine?

Yes I'd like to. But I have my hands full at the moment. I have like 5 projects piled up right now 🤦🏻‍♀️
